name: BabyShop
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cloudinary_public: ^0.21.0
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.1
  local_auth: ^2.1.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/apple_logo.png
